services:
  - type: web
    name: web
    env: docker
    dockerContext: ./client
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: development
      - key: DATABASE_URL
        value: postgresql://user:1234@db:5432/notes_db

  - type: pserv
    name: db
    env: docker
    dockerContext: ./database
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        value: 1234
      - key: POSTGRES_DB
        value: notes_db

